/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project1.pptk.view;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import project1.pptk.controller.BarangController;
import project1.pptk.database.pptkDatabase;
import project1.pptk.entity.Barang;
import project1.pptk.error.BarangException;
import project1.pptk.event.BarangListener;
import project1.pptk.model.BarangModel;
import project1.pptk.model.TabelBarangModel;
import project1.pptk.service.BarangDao;

/**
 *
 * @author LENOVO
 */
public class PPTKMainView extends javax.swing.JFrame implements BarangListener, ListSelectionListener {

    /**
     * Creates new form PPTKMainView
     */
    private TabelBarangModel tabelModel;
    private BarangModel model;
    private BarangController controller;

    public PPTKMainView() {
        tabelModel = new TabelBarangModel();

        model = new BarangModel();
        model.setListener(this);
        
        controller =  new BarangController();
        controller.setModel(model);
        
        initComponents();

        tabelBarang.getSelectionModel().addListSelectionListener(this);
        tabelBarang.setModel(tabelModel);
    }

    public JTable getTabelBarang() {
        return tabelBarang;
    }

    public JTextField getTxtBarang() {
        return txtBarang;
    }

    public JTextField getTxtBarang2() {
        return txtBarang2;
    }

    public JTextField getTxtCari() {
        return txtCari;
    }

    public JTextField getTxtHarga() {
        return txtHarga;
    }

    public JTextField getTxtHarga2() {
        return txtHarga2;
    }

    public JTextField getTxtNo() {
        return txtNo;
    }

    public JTextField getTxtNo2() {
        return txtNo2;
    }
    
    public JTextField getTxtQty() {
        return txtQty;
    }

    public JTextField getTxtQty2() {
        return txtQty2;
    }

    public JTextField getTxtSatuan() {
        return txtSatuan;
    }

    public JTextField getTxtSatuan2() {
        return txtSatuan2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        menuKiri = new javax.swing.JPanel();
        menuJudul = new javax.swing.JPanel();
        jJudul = new javax.swing.JLabel();
        menuDatabase = new javax.swing.JPanel();
        iconDatabase = new javax.swing.JLabel();
        menuTambah = new javax.swing.JPanel();
        iconTambah = new javax.swing.JLabel();
        menuUnduh = new javax.swing.JPanel();
        iconUnduh = new javax.swing.JLabel();
        menuLogout = new javax.swing.JPanel();
        jLogout = new javax.swing.JLabel();
        menuKanan = new javax.swing.JPanel();
        itemDatabase = new javax.swing.JPanel();
        jDataGudang = new javax.swing.JLabel();
        jCari = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        jBarang2 = new javax.swing.JLabel();
        jSatuan2 = new javax.swing.JLabel();
        jQty2 = new javax.swing.JLabel();
        jHarga2 = new javax.swing.JLabel();
        jNo2 = new javax.swing.JLabel();
        txtNo2 = new javax.swing.JTextField();
        txtHarga2 = new javax.swing.JTextField();
        txtSatuan2 = new javax.swing.JTextField();
        txtBarang2 = new javax.swing.JTextField();
        txtQty2 = new javax.swing.JTextField();
        btnHapus = new javax.swing.JPanel();
        iconHapus = new javax.swing.JLabel();
        btnEdit = new javax.swing.JPanel();
        iconEdit = new javax.swing.JLabel();
        itemTambah = new javax.swing.JPanel();
        jTambah = new javax.swing.JLabel();
        pTambahBarang = new javax.swing.JPanel();
        jNo = new javax.swing.JLabel();
        jBarang = new javax.swing.JLabel();
        jQty = new javax.swing.JLabel();
        jSatuan = new javax.swing.JLabel();
        jHarga = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        txtBarang = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        txtSatuan = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        btnTambah = new javax.swing.JPanel();
        iconjTambah = new javax.swing.JLabel();
        btnReset = new javax.swing.JPanel();
        iconjReset = new javax.swing.JLabel();
        itemUnduh = new javax.swing.JPanel();
        panelUnduh = new javax.swing.JPanel();
        iconUnduh2 = new javax.swing.JLabel();
        jUnduh = new javax.swing.JLabel();
        itemAwal = new javax.swing.JPanel();
        jJudulKanan = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        iconPPTK = new javax.swing.JLabel();
        panelIsi = new javax.swing.JPanel();
        iconUser = new javax.swing.JLabel();
        iconPass = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogin = new javax.swing.JPanel();
        jLogin = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DATABASE PPTK GAMBUNG ");
        setResizable(false);

        panelMenu.setBackground(new java.awt.Color(157, 158, 158));
        panelMenu.setPreferredSize(new java.awt.Dimension(600, 400));
        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.LINE_AXIS));

        menuKiri.setBackground(new java.awt.Color(59, 59, 59));

        menuJudul.setBackground(new java.awt.Color(59, 59, 59));

        jJudul.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jJudul.setForeground(new java.awt.Color(255, 255, 255));
        jJudul.setText("Pengadaan");

        javax.swing.GroupLayout menuJudulLayout = new javax.swing.GroupLayout(menuJudul);
        menuJudul.setLayout(menuJudulLayout);
        menuJudulLayout.setHorizontalGroup(
            menuJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuJudulLayout.setVerticalGroup(
            menuJudulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuJudulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jJudul)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        menuDatabase.setBackground(new java.awt.Color(59, 59, 59));
        menuDatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuDatabaseMouseClicked(evt);
            }
        });

        iconDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/Barang-icon.png"))); // NOI18N

        javax.swing.GroupLayout menuDatabaseLayout = new javax.swing.GroupLayout(menuDatabase);
        menuDatabase.setLayout(menuDatabaseLayout);
        menuDatabaseLayout.setHorizontalGroup(
            menuDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDatabaseLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(iconDatabase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuDatabaseLayout.setVerticalGroup(
            menuDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuDatabaseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(iconDatabase)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        menuTambah.setBackground(new java.awt.Color(59, 59, 59));
        menuTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuTambahMouseClicked(evt);
            }
        });

        iconTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/tambah-icon-big.png"))); // NOI18N

        javax.swing.GroupLayout menuTambahLayout = new javax.swing.GroupLayout(menuTambah);
        menuTambah.setLayout(menuTambahLayout);
        menuTambahLayout.setHorizontalGroup(
            menuTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuTambahLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(iconTambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuTambahLayout.setVerticalGroup(
            menuTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuTambahLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(iconTambah)
                .addGap(20, 20, 20))
        );

        menuUnduh.setBackground(new java.awt.Color(59, 59, 59));
        menuUnduh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuUnduhMouseClicked(evt);
            }
        });

        iconUnduh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/unduh.png"))); // NOI18N

        javax.swing.GroupLayout menuUnduhLayout = new javax.swing.GroupLayout(menuUnduh);
        menuUnduh.setLayout(menuUnduhLayout);
        menuUnduhLayout.setHorizontalGroup(
            menuUnduhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuUnduhLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(iconUnduh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuUnduhLayout.setVerticalGroup(
            menuUnduhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuUnduhLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(iconUnduh)
                .addGap(25, 25, 25))
        );

        menuLogout.setBackground(new java.awt.Color(59, 59, 59));
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuLogoutMouseExited(evt);
            }
        });

        jLogout.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLogout.setForeground(new java.awt.Color(255, 255, 255));
        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/LOGOUT.png"))); // NOI18N
        jLogout.setText("LOGOUT");

        javax.swing.GroupLayout menuLogoutLayout = new javax.swing.GroupLayout(menuLogout);
        menuLogout.setLayout(menuLogoutLayout);
        menuLogoutLayout.setHorizontalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuLogoutLayout.setVerticalGroup(
            menuLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuKiriLayout = new javax.swing.GroupLayout(menuKiri);
        menuKiri.setLayout(menuKiriLayout);
        menuKiriLayout.setHorizontalGroup(
            menuKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuUnduh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menuDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuKiriLayout.setVerticalGroup(
            menuKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuKiriLayout.createSequentialGroup()
                .addComponent(menuJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuUnduh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMenu.add(menuKiri);

        menuKanan.setBackground(new java.awt.Color(157, 158, 158));

        itemDatabase.setBackground(new java.awt.Color(157, 158, 158));
        itemDatabase.setPreferredSize(new java.awt.Dimension(483, 418));

        jDataGudang.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jDataGudang.setForeground(new java.awt.Color(255, 255, 255));
        jDataGudang.setText("Data Gudang");

        jCari.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jCari.setForeground(new java.awt.Color(255, 255, 255));
        jCari.setText("Cari : ");

        txtCari.setBackground(new java.awt.Color(157, 158, 158));
        txtCari.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtCari.setForeground(new java.awt.Color(255, 255, 255));
        txtCari.setBorder(null);
        txtCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCariMouseClicked(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));

        tabelBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelBarang);

        jBarang2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jBarang2.setForeground(new java.awt.Color(255, 255, 255));
        jBarang2.setText("Barang :");

        jSatuan2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jSatuan2.setForeground(new java.awt.Color(255, 255, 255));
        jSatuan2.setText("Satuan :");

        jQty2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jQty2.setForeground(new java.awt.Color(255, 255, 255));
        jQty2.setText("Qty :");

        jHarga2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jHarga2.setForeground(new java.awt.Color(255, 255, 255));
        jHarga2.setText("Harga :");

        jNo2.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jNo2.setForeground(new java.awt.Color(255, 255, 255));
        jNo2.setText("No :");

        txtNo2.setEditable(false);
        txtNo2.setBackground(new java.awt.Color(102, 102, 102));
        txtNo2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNo2.setForeground(new java.awt.Color(255, 255, 255));
        txtNo2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtHarga2.setBackground(new java.awt.Color(102, 102, 102));
        txtHarga2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtHarga2.setForeground(new java.awt.Color(255, 255, 255));
        txtHarga2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtSatuan2.setBackground(new java.awt.Color(102, 102, 102));
        txtSatuan2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtSatuan2.setForeground(new java.awt.Color(255, 255, 255));
        txtSatuan2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtBarang2.setBackground(new java.awt.Color(102, 102, 102));
        txtBarang2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtBarang2.setForeground(new java.awt.Color(255, 255, 255));
        txtBarang2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtQty2.setBackground(new java.awt.Color(102, 102, 102));
        txtQty2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtQty2.setForeground(new java.awt.Color(255, 255, 255));
        txtQty2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHapus.setBackground(new java.awt.Color(71, 71, 71));
        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
        });

        iconHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/delete-icon.png"))); // NOI18N

        javax.swing.GroupLayout btnHapusLayout = new javax.swing.GroupLayout(btnHapus);
        btnHapus.setLayout(btnHapusLayout);
        btnHapusLayout.setHorizontalGroup(
            btnHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHapusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconHapus))
        );
        btnHapusLayout.setVerticalGroup(
            btnHapusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHapusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconHapus)
                .addContainerGap())
        );

        btnEdit.setBackground(new java.awt.Color(71, 71, 71));
        btnEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
        });

        iconEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/update-icon.png"))); // NOI18N

        javax.swing.GroupLayout btnEditLayout = new javax.swing.GroupLayout(btnEdit);
        btnEdit.setLayout(btnEditLayout);
        btnEditLayout.setHorizontalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(iconEdit))
        );
        btnEditLayout.setVerticalGroup(
            btnEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnEditLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(iconEdit)
                .addContainerGap())
        );

        javax.swing.GroupLayout itemDatabaseLayout = new javax.swing.GroupLayout(itemDatabase);
        itemDatabase.setLayout(itemDatabaseLayout);
        itemDatabaseLayout.setHorizontalGroup(
            itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemDatabaseLayout.createSequentialGroup()
                .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemDatabaseLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(itemDatabaseLayout.createSequentialGroup()
                                .addComponent(jCari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                    .addComponent(txtCari)))
                            .addGroup(itemDatabaseLayout.createSequentialGroup()
                                .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jQty2)
                                    .addComponent(jBarang2)
                                    .addComponent(jNo2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBarang2)
                                    .addComponent(txtQty2)
                                    .addComponent(txtNo2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSatuan2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jHarga2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSatuan2, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(txtHarga2))
                                .addGap(10, 10, 10)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(itemDatabaseLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jDataGudang)))
                .addGap(38, 38, 38))
        );
        itemDatabaseLayout.setVerticalGroup(
            itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDatabaseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jDataGudang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemDatabaseLayout.createSequentialGroup()
                        .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNo2)
                            .addComponent(txtNo2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(txtSatuan2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(jSatuan2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBarang2)
                            .addComponent(txtBarang2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(jHarga2)
                            .addComponent(txtHarga2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jQty2))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, itemDatabaseLayout.createSequentialGroup()
                        .addGroup(itemDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))))
        );

        itemTambah.setBackground(new java.awt.Color(157, 158, 158));

        jTambah.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jTambah.setForeground(new java.awt.Color(255, 255, 255));
        jTambah.setText("Tambah Barang");

        pTambahBarang.setBackground(new java.awt.Color(59, 59, 59));

        jNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jNo.setForeground(new java.awt.Color(255, 255, 255));
        jNo.setText("No");

        jBarang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBarang.setForeground(new java.awt.Color(255, 255, 255));
        jBarang.setText("Barang");

        jQty.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jQty.setForeground(new java.awt.Color(255, 255, 255));
        jQty.setText("Qty");

        jSatuan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jSatuan.setForeground(new java.awt.Color(255, 255, 255));
        jSatuan.setText("Satuan");

        jHarga.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jHarga.setForeground(new java.awt.Color(255, 255, 255));
        jHarga.setText("Harga");

        txtNo.setEditable(false);
        txtNo.setBackground(new java.awt.Color(59, 59, 59));
        txtNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtNo.setForeground(new java.awt.Color(255, 255, 255));
        txtNo.setBorder(null);

        txtBarang.setBackground(new java.awt.Color(59, 59, 59));
        txtBarang.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtBarang.setForeground(new java.awt.Color(255, 255, 255));
        txtBarang.setBorder(null);
        txtBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBarangMouseClicked(evt);
            }
        });

        txtQty.setBackground(new java.awt.Color(59, 59, 59));
        txtQty.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtQty.setForeground(new java.awt.Color(255, 255, 255));
        txtQty.setBorder(null);
        txtQty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQtyMouseClicked(evt);
            }
        });

        txtSatuan.setBackground(new java.awt.Color(59, 59, 59));
        txtSatuan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtSatuan.setForeground(new java.awt.Color(255, 255, 255));
        txtSatuan.setBorder(null);
        txtSatuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSatuanMouseClicked(evt);
            }
        });

        txtHarga.setBackground(new java.awt.Color(59, 59, 59));
        txtHarga.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(255, 255, 255));
        txtHarga.setBorder(null);
        txtHarga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHargaMouseClicked(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        btnTambah.setBackground(new java.awt.Color(27, 27, 27));
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
        });

        iconjTambah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        iconjTambah.setForeground(new java.awt.Color(255, 255, 255));
        iconjTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/tambah-icon-small.png"))); // NOI18N
        iconjTambah.setText("Tambah");

        javax.swing.GroupLayout btnTambahLayout = new javax.swing.GroupLayout(btnTambah);
        btnTambah.setLayout(btnTambahLayout);
        btnTambahLayout.setHorizontalGroup(
            btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTambahLayout.createSequentialGroup()
                .addComponent(iconjTambah)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        btnTambahLayout.setVerticalGroup(
            btnTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTambahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconjTambah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReset.setBackground(new java.awt.Color(27, 27, 27));
        btnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnResetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetMouseExited(evt);
            }
        });

        iconjReset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        iconjReset.setForeground(new java.awt.Color(255, 255, 255));
        iconjReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/MAXIMIZE.png"))); // NOI18N
        iconjReset.setText("Reset");

        javax.swing.GroupLayout btnResetLayout = new javax.swing.GroupLayout(btnReset);
        btnReset.setLayout(btnResetLayout);
        btnResetLayout.setHorizontalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnResetLayout.createSequentialGroup()
                .addComponent(iconjReset)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        btnResetLayout.setVerticalGroup(
            btnResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnResetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconjReset)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pTambahBarangLayout = new javax.swing.GroupLayout(pTambahBarang);
        pTambahBarang.setLayout(pTambahBarangLayout);
        pTambahBarangLayout.setHorizontalGroup(
            pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTambahBarangLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jNo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBarang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jQty, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSatuan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jHarga, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBarang)
                    .addComponent(jSeparator4)
                    .addComponent(txtSatuan)
                    .addComponent(jSeparator6)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(txtNo, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(txtQty, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTambahBarangLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pTambahBarangLayout.setVerticalGroup(
            pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTambahBarangLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jNo)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBarang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBarang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jQty, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSatuan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSatuan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHarga)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pTambahBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout itemTambahLayout = new javax.swing.GroupLayout(itemTambah);
        itemTambah.setLayout(itemTambahLayout);
        itemTambahLayout.setHorizontalGroup(
            itemTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemTambahLayout.createSequentialGroup()
                .addGroup(itemTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(itemTambahLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jTambah))
                    .addGroup(itemTambahLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(pTambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        itemTambahLayout.setVerticalGroup(
            itemTambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemTambahLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pTambahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        itemUnduh.setBackground(new java.awt.Color(157, 158, 158));

        panelUnduh.setBackground(new java.awt.Color(59, 59, 59));

        iconUnduh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/unduh.png"))); // NOI18N

        jUnduh.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jUnduh.setForeground(new java.awt.Color(255, 255, 255));
        jUnduh.setText("unduh");

        javax.swing.GroupLayout panelUnduhLayout = new javax.swing.GroupLayout(panelUnduh);
        panelUnduh.setLayout(panelUnduhLayout);
        panelUnduhLayout.setHorizontalGroup(
            panelUnduhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnduhLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(iconUnduh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jUnduh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );
        panelUnduhLayout.setVerticalGroup(
            panelUnduhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUnduhLayout.createSequentialGroup()
                .addGroup(panelUnduhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUnduhLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(iconUnduh2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelUnduhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jUnduh, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout itemUnduhLayout = new javax.swing.GroupLayout(itemUnduh);
        itemUnduh.setLayout(itemUnduhLayout);
        itemUnduhLayout.setHorizontalGroup(
            itemUnduhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemUnduhLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(panelUnduh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(96, 96, 96))
        );
        itemUnduhLayout.setVerticalGroup(
            itemUnduhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemUnduhLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(panelUnduh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jJudulKanan.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jJudulKanan.setForeground(new java.awt.Color(59, 59, 59));
        jJudulKanan.setText("Silahkan Pilih Menu");

        javax.swing.GroupLayout itemAwalLayout = new javax.swing.GroupLayout(itemAwal);
        itemAwal.setLayout(itemAwalLayout);
        itemAwalLayout.setHorizontalGroup(
            itemAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemAwalLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jJudulKanan)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        itemAwalLayout.setVerticalGroup(
            itemAwalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itemAwalLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jJudulKanan)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuKananLayout = new javax.swing.GroupLayout(menuKanan);
        menuKanan.setLayout(menuKananLayout);
        menuKananLayout.setHorizontalGroup(
            menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
            .addGroup(menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(itemTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuKananLayout.createSequentialGroup()
                    .addComponent(itemDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(itemUnduh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(menuKananLayout.createSequentialGroup()
                    .addComponent(itemAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        menuKananLayout.setVerticalGroup(
            menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
            .addGroup(menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(itemTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(itemDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
            .addGroup(menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(itemUnduh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(itemAwal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu.add(menuKanan);

        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconPPTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/LOGO-GAMBUNG.png"))); // NOI18N
        panelLogin.add(iconPPTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, 150));

        panelIsi.setBackground(new java.awt.Color(153, 153, 153));
        panelIsi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/PROFILE.png"))); // NOI18N

        iconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/PASSWORD.png"))); // NOI18N

        txtUsername.setBackground(new java.awt.Color(153, 153, 153));
        txtUsername.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtUsername.setText("USERNAME");
        txtUsername.setBorder(null);
        txtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsernameMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        txtPassword.setBackground(new java.awt.Color(153, 153, 153));
        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setText("  PASSWORD");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelIsiLayout = new javax.swing.GroupLayout(panelIsi);
        panelIsi.setLayout(panelIsiLayout);
        panelIsiLayout.setHorizontalGroup(
            panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsiLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iconUser)
                    .addComponent(iconPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelIsiLayout.setVerticalGroup(
            panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIsiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelIsiLayout.createSequentialGroup()
                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1))
                    .addComponent(iconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIsiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 9, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelLogin.add(panelIsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        btnLogin.setBackground(new java.awt.Color(153, 153, 153));
        btnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        jLogin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLogin.setText("LOGIN");

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 60, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project1/pptk/icon/bgLogin.png"))); // NOI18N
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backgroundMouseEntered(evt);
            }
        });
        panelLogin.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Color Tua = new Color(27, 27, 27);
    Color Normal = new Color(59, 59, 59);
    Color Normal2 = new Color(71, 71, 71);
    private void txtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsernameMouseClicked
        // TODO add your handling code here:
        txtUsername.setText("");
    }//GEN-LAST:event_txtUsernameMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        String Username;
        String Password;
        Username = txtUsername.getText();
        Password = txtPassword.getText();

        if ((Username.equals("PPTK")) && (Password.equals("Gambung"))) {
            panelLogin.setVisible(false);
            panelMenu.setVisible(true);
            menuKiri.setVisible(true);
            menuKanan.setVisible(true);

            itemAwal.setVisible(true);
            itemDatabase.setVisible(false);
            itemTambah.setVisible(false);
            itemUnduh.setVisible(false);

            txtUsername.setText("USERNAME");
            txtPassword.setText("PASSWORD");
            
            controller.resetBarang(this);
        } else {
            JOptionPane.showMessageDialog(panelLogin, "Username atau Password salah !");
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(panelMenu, "Anda yakin akan keluar?")==JOptionPane.OK_OPTION) {
        panelLogin.setVisible(true);
        panelMenu.setVisible(false);
        menuKiri.setVisible(false);
        menuKanan.setVisible(false);

        itemAwal.setVisible(false);
        itemDatabase.setVisible(false);
        itemTambah.setVisible(false);
        itemUnduh.setVisible(false);

        menuDatabase.setBackground(Normal);
        menuTambah.setBackground(Normal);
        menuUnduh.setBackground(Normal);
        }
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void menuLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseEntered
        // TODO add your handling code here:
        menuLogout.setBackground(Tua);
    }//GEN-LAST:event_menuLogoutMouseEntered

    private void menuLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseExited
        // TODO add your handling code here:
        menuLogout.setBackground(Normal);
    }//GEN-LAST:event_menuLogoutMouseExited

    private void backgroundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseEntered
        // TODO add your handling code here:
        panelLogin.setVisible(true);
        panelMenu.setVisible(false);
    }//GEN-LAST:event_backgroundMouseEntered

    private void menuUnduhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUnduhMouseClicked
        // TODO add your handling code here:
        menuDatabase.setBackground(Normal);
        menuTambah.setBackground(Normal);
        menuUnduh.setBackground(Tua);

        itemAwal.setVisible(false);
        itemDatabase.setVisible(false);
        itemTambah.setVisible(false);
        itemUnduh.setVisible(true);
        
        txtBarang2.setText(null);
        txtQty2.setText(null);
        txtSatuan2.setText(null);
        txtHarga2.setText(null);
    }//GEN-LAST:event_menuUnduhMouseClicked

    private void menuDatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuDatabaseMouseClicked
        // TODO add your handling code here:
        menuDatabase.setBackground(Tua);
        menuTambah.setBackground(Normal);
        menuUnduh.setBackground(Normal);

        itemAwal.setVisible(false);
        itemDatabase.setVisible(true);
        itemTambah.setVisible(false);
        itemUnduh.setVisible(false);
    }//GEN-LAST:event_menuDatabaseMouseClicked

    private void menuTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuTambahMouseClicked
        // TODO add your handling code here:
        menuDatabase.setBackground(Normal);
        menuTambah.setBackground(Tua);
        menuUnduh.setBackground(Normal);

        itemAwal.setVisible(false);
        itemDatabase.setVisible(false);
        itemTambah.setVisible(true);
        itemUnduh.setVisible(false);
        
        controller.resetBarang(this);
    }//GEN-LAST:event_menuTambahMouseClicked

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        // TODO add your handling code here:
        btnTambah.setBackground(Normal);
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        // TODO add your handling code here:
        btnTambah.setBackground(Tua);
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        // TODO add your handling code here:
        btnHapus.setBackground(Tua);
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        // TODO add your handling code here:
        btnHapus.setBackground(Normal2);
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        // TODO add your handling code here:
        btnEdit.setBackground(Tua);
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        // TODO add your handling code here:
        btnEdit.setBackground(Normal2);
    }//GEN-LAST:event_btnEditMouseExited

    private void btnResetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseEntered
        // TODO add your handling code here:
        btnReset.setBackground(Normal);
    }//GEN-LAST:event_btnResetMouseEntered

    private void btnResetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseExited
        // TODO add your handling code here:
        btnReset.setBackground(Tua);
    }//GEN-LAST:event_btnResetMouseExited

    private void btnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetMouseClicked
        // TODO add your handling code here:
        controller.resetBarang(this);
    }//GEN-LAST:event_btnResetMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
        controller.insertBarang(this);
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        // TODO add your handling code here:
        controller.updateBarang(this);
        
        txtNo2.setText(null);
        txtBarang2.setText(null);
        txtQty2.setText(null);
        txtSatuan2.setText(null);
        txtHarga2.setText(null);
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
        // TODO add your handling code here:
        controller.deleteBarang(this);
        
        txtNo2.setText(null);
        txtBarang2.setText(null);
        txtQty2.setText(null);
        txtSatuan2.setText(null);
        txtHarga2.setText(null);
    }//GEN-LAST:event_btnHapusMouseClicked

    private void txtCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCariMouseClicked
        // TODO add your handling code here:
        txtCari.setText("");
    }//GEN-LAST:event_txtCariMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBarangMouseClicked
        // TODO add your handling code here:
        txtBarang.setText("");
    }//GEN-LAST:event_txtBarangMouseClicked

    private void txtQtyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtQtyMouseClicked
        // TODO add your handling code here:
        txtQty.setText("");
    }//GEN-LAST:event_txtQtyMouseClicked

    private void txtSatuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSatuanMouseClicked
        // TODO add your handling code here:
        txtSatuan.setText("");
    }//GEN-LAST:event_txtSatuanMouseClicked

    private void txtHargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHargaMouseClicked
        // TODO add your handling code here:
        txtHarga.setText("");
    }//GEN-LAST:event_txtHargaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel btnEdit;
    private javax.swing.JPanel btnHapus;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel btnReset;
    private javax.swing.JPanel btnTambah;
    private javax.swing.JLabel iconDatabase;
    private javax.swing.JLabel iconEdit;
    private javax.swing.JLabel iconHapus;
    private javax.swing.JLabel iconPPTK;
    private javax.swing.JLabel iconPass;
    private javax.swing.JLabel iconTambah;
    private javax.swing.JLabel iconUnduh;
    private javax.swing.JLabel iconUnduh2;
    private javax.swing.JLabel iconUser;
    private javax.swing.JLabel iconjReset;
    private javax.swing.JLabel iconjTambah;
    private javax.swing.JPanel itemAwal;
    private javax.swing.JPanel itemDatabase;
    private javax.swing.JPanel itemTambah;
    private javax.swing.JPanel itemUnduh;
    private javax.swing.JLabel jBarang;
    private javax.swing.JLabel jBarang2;
    private javax.swing.JLabel jCari;
    private javax.swing.JLabel jDataGudang;
    private javax.swing.JLabel jHarga;
    private javax.swing.JLabel jHarga2;
    private javax.swing.JLabel jJudul;
    private javax.swing.JLabel jJudulKanan;
    private javax.swing.JLabel jLogin;
    private javax.swing.JLabel jLogout;
    private javax.swing.JLabel jNo;
    private javax.swing.JLabel jNo2;
    private javax.swing.JLabel jQty;
    private javax.swing.JLabel jQty2;
    private javax.swing.JLabel jSatuan;
    private javax.swing.JLabel jSatuan2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jTambah;
    private javax.swing.JLabel jUnduh;
    private javax.swing.JPanel menuDatabase;
    private javax.swing.JPanel menuJudul;
    private javax.swing.JPanel menuKanan;
    private javax.swing.JPanel menuKiri;
    private javax.swing.JPanel menuLogout;
    private javax.swing.JPanel menuTambah;
    private javax.swing.JPanel menuUnduh;
    private javax.swing.JPanel pTambahBarang;
    private javax.swing.JPanel panelIsi;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelUnduh;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JTextField txtBarang2;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHarga2;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtNo2;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtQty2;
    private javax.swing.JTextField txtSatuan;
    private javax.swing.JTextField txtSatuan2;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChange(BarangModel model) {
        txtNo.setText(model.getNo() + "");
        txtBarang.setText(model.getNama());
        txtQty.setText(model.getQty() + "");
        txtSatuan.setText(model.getSatuan());
        txtHarga.setText(model.getHarga_satuan() + "");
    }

    @Override
    public void onInsert(Barang barang) {
        tabelModel.add(barang);
    }

    @Override
    public void onUpdate(Barang barang) {
        int index = tabelBarang.getSelectedRow();
        tabelModel.set(index, barang);
    }

    @Override
    public void onDelete() {
        int index = tabelBarang.getSelectedRow();
        tabelModel.remove(index);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        try {
            Barang model = tabelModel.get(tabelBarang.getSelectedRow());
            txtNo2.setText(model.getNo()+"");
            txtBarang2.setText(model.getNama());
            txtQty2.setText(model.getQty() + "");
            txtSatuan2.setText(model.getSatuan());
            txtHarga2.setText(model.getHarga_satuan()+ "");
        } catch (IndexOutOfBoundsException exception) {
        }
    }
    
    public void loadDatabase() throws SQLException, BarangException{
        BarangDao dao = new pptkDatabase().getBarangDao();
        tabelModel.setList(dao.selectAllBarang());
    }
}
